---
baseurl: "https://lifewithalacrity.github.io/"
languageCode: "en-us"
title: "Life With Alacrity"
theme: indie-tufte

permalinks:
  post: /:year/:month/:title/

publishdir: "../../lifewithalacrity.github.io"

taxonomies:
  tag: "tags"

params:
  name: "Life With Alacrity"
  summary: "A blog on social software, collaboration, trust, security, privacy, and internet tools"
  author: "Christopher Allen"
  authorurl: "/about"

