---
baseurl: "https://lifewithalacrity.github.io/"
languageCode: "en-us"
title: "Life With Alacrity"

permalinks:
  post: /:year/:month/:title/

publishdir: "../../lifewithalacrity.github.io"

params:
  description: "A blog on social software, collaboration, trust, security, privacy, and internet tools, by Christopher Allen."
  author: "Christopher Allen"
  name: "Life With Alacrity"